### ISSUE TITLE
Destacar los márgenes de los polígonos sin opacidad

### ISSUE THREAD

**Issue by nelanthas** [geowe/ogv#20]
Buenas, al realizar un mapa temático, cuando se muestran los polígonos sin opacidad y coinciden varios polígonos del mismo color adyacentes, no se pueden distinguir unos de otros.

¿Sería posible resaltar el borde de los polígonos?
![Captura](https://user-images.githubusercontent.com/5320396/79670619-adf04800-81c4-11ea-9704-d35c9f98212b.JPG)

En la captura aparece una zona azul clara que en realidad contiene dos polígonos.
![Captura2](https://user-images.githubusercontent.com/5320396/79670631-cc564380-81c4-11ea-972b-df8d9a18877f.JPG)

Un saludo.

**Comment by jmmluna** [comment]
Ya está resuelto en la versión 2.15. Ahora se puede especificar en la url los siguientes parámetros:
**stroke-color:** código hexadecimal del color del borde de la línea (sin #)
**stroke-width:** número entero que indica el ancho de la línea (1 es el valor por defecto)

**Nota**: también se ha mejorado la visualización del etiquetado en los elementos aplicando el tamaño de fuente en función de la resolución del mapa.

Aquí tienes un ejemplo:
https://geowe.org/ogv/viewer/?geojson=https://raw.githubusercontent.com/jmmluna/geodata/master/ogv/capa-cordoba-cpostal_WGS84.geojson&alpha=1&stroke-color=FF0000&stroke-color=2&label=COD_POSTAL

![imagen](https://user-images.githubusercontent.com/17873390/80264735-5b67cd80-8695-11ea-980a-6898adf4197c.png)
